// <auto-generated />
using System;
using FoodIdea.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodIdea.API.Migrations
{
    [DbContext(typeof(FoodIdeaContext))]
    [Migration("20220902124615_FoodIdeaDBInitialMigration")]
    partial class FoodIdeaDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodIdea.API.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHardToDo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<double>("TasteRate")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe+IngredientsClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientsClass");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe", b =>
                {
                    b.HasOne("FoodIdea.API.Entities.Food", "Food")
                        .WithMany("Recipe")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe+IngredientsClass", b =>
                {
                    b.HasOne("FoodIdea.API.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Food", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
