// <auto-generated />
using FoodIdea.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodIdea.API.Migrations
{
    [DbContext(typeof(FoodIdeaContext))]
    partial class FoodIdeaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodIdea.API.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Włoskie danie z makaronem i mięsem mielonym",
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Meksykańskie danie z fasoli czerwonej, białej, mięsa mielonego oraz kukurydzy",
                            Name = "Chilli con-carne"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Danie składające się z losowych warzyw, ryżu, opcjonalnie jakieś mięso",
                            Name = "Mix warzywny"
                        });
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("HowToMake")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHardToDo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<double>("TasteRate")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodId = 1,
                            HowToMake = "Ugotuj makaron, usmaz mieso, dodaj sos",
                            IsHardToDo = false,
                            PreparationTime = 30,
                            TasteRate = 8.0
                        },
                        new
                        {
                            Id = 2,
                            FoodId = 2,
                            HowToMake = "Usmaz mieso, dodaj fasole, zrob sos",
                            IsHardToDo = false,
                            PreparationTime = 20,
                            TasteRate = 8.5
                        },
                        new
                        {
                            Id = 3,
                            FoodId = 3,
                            HowToMake = "Usmaz mieso, dodaj warzywa, dodaj odpowiednie przyprawy",
                            IsHardToDo = false,
                            PreparationTime = 20,
                            TasteRate = 7.0
                        });
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Recipe", b =>
                {
                    b.HasOne("FoodIdea.API.Entities.Food", "Food")
                        .WithMany("Recipe")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodIdea.API.Entities.Food", b =>
                {
                    b.Navigation("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
